# Generated by Django 5.0.6 on 2024-06-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_info', '0002_setup_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=90)),
                ('phone', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='setup',
        ),
    ]
